### ISSUE TITLE
IKucoinSocketClient - Connection is lost without restore

### ISSUE THREAD

**Issue by masherak** [JKorf/Kucoin.Net#140]
Property AutoReconnect is set to true.

Randomly between 2-3 days is connection via WS lost without restore, I can see it because I log all subscription events.

But I can see sometimes is connection restored without problem so restoring is working in some cases, but in some not.

I use also your Binance library and there is no problem with this.

Thank you for your help
Have a nice day

Jaroslav Klíma

**Comment by JKorf** [comment]
The Binance and Kucoin use the same implementation for reconnecting, so there should be no difference in the behavior of the 2. Can you share some logging?

**Comment by keyvanme** [comment]
I have the same problem. After 2 or 3 days I get "error 401 unauthorized " and connection cannot restore.
I use .net framework 5

**Comment by JKorf** [comment]
Hm weird. Do you have any logging of when that happens?

**Comment by masherak** [comment]
I will try to get some logs, but now I had to restart my app very often so I have not gotten into this state for a long time, I will let you know.

**Comment by masherak** [comment]
@JKorf  I have never seen this problem before 24h of running the WS connection. Before 24h I can see the "connection lost" event is triggered and immediately after that "ConnectionRestored" is fired, restoring took 1-1.5s. But after approximately 24h there is fired only "ConnectionLost" and never restored.

Which information I can provide to you for help?

**Comment by JKorf** [comment]
Can you try getting some logging? Trace logging would be ideal, but enabling trace logging will produce a lot of log entries, so I'm not sure if that's doable for your application. Else Debug logging would also help.
You can change the log level in the client options

**Comment by JKorf** [comment]
I've found a timing issue in the reconnection logic where it could sometimes cause the reconnect loop to stop without notification or anything. This should be resolved in the latest version

**Comment by masherak** [comment]
Perfect! I will try it and let you know. Thank you very much

**Comment by masherak** [comment]
@JKorf It looks like it works great! Thank you very much!

**Comment by masherak** [comment]
@JKorf After one and half month I can see that problem persist(to a much lesser extent than before). The frequency is very low, 3-4 times per 50 days is connection lost without restore. In Binance library never happens something like this, only Kucoin. I looked at your code, but I am not able to find where problem can be.

**Comment by masherak** [comment]
@JKorf Please, can you look to your email, I sent you private request. Thank you

**Comment by JKorf** [comment]
I think I've found the issue. To create a connection to the server a request has to be made to a REST endpoint to get a token to use for the connection. It seems that after some time this token expires and the server rejects connection requests using this. So when trying to reconnect when connection is lost after an x period after creating the initial token request the server will keep rejecting the token and a reconnect is never possible.

I'm currently testing a fix which involves having the client do a new token request when reconnecting.

**Comment by masherak** [comment]
@JKorf Perfect, thank you very much, please let me know in which version the fix will be. Have a nice day

**Comment by JKorf** [comment]
The latest version (4.0.15) has the fix. Let me know if that works for you

**Comment by vgpro54321** [comment]
> I think I've found the issue. To create a connection to the server a request has to be made to a REST endpoint to get a token to use for the connection. It seems that after some time this token expires and the server rejects connection requests using this. So when trying to reconnect when connection is lost after an x period after creating the initial token request the server will keep rejecting the token and a reconnect is never possible.
> 
> I'm currently testing a fix which involves having the client do a new token request when reconnecting.

Figured as much, was going to submit an issue but it looks you have just fixed it. Will try and revert.

**Comment by JKorf** [comment]
I'll assume there haven't been any issues. If so feel free to re-open
