### ISSUE TITLE
Question about Socket PositionUpdates

### ISSUE THREAD

**Issue by shahrooztk** [JKorf/Kucoin.Net#62]
Hi JKorf.
I have a problem in SubscribeToPositionUpdates method.
When I use SubscribeToPositionUpdatesAsync in socket , like the code below :

`await client.Futures.SubscribeToPositionUpdatesAsync("DENTUSDTM", data => { var dd = data; });`

All items in Data is empty ! , like this : [https://i.postimg.cc/HkTWYrpY/git.jpg](url)

My code : [https://i.postimg.cc/NjRXV9dQ/git2.jpg](url)

This problem is only in this method and in other methods there is no problem (Socket).

I also used the latest version (V 3.1.1).

**Comment by JKorf** [comment]
Can you check what data is sent in the socket?

**Comment by shahrooztk** [comment]
Hi again.
I have a problem with this method and all data is null.
I open a new position, then make changes to it (manually) , But this socket method does not seem to pay attention to the opening and closing of my positions or their moment-by-moment reporting in my account.

I will send you code and the pictures related to the tests I did. Check to see the problem of my work.

I created a position manually in currency, In my Kucoin Futures account (DENTUSDTM). Then i used SubscribeToPositionUpdatesAsync  method but all data is null.

This is my code:
```
var client = new KucoinSocketClient(new KucoinSocketClientOptions() 
{
    FuturesApiCredentials = new KucoinApiCredentials("******", "******", "******"),
    OutputOriginalData = true,
    LogLevel = Microsoft.Extensions.Logging.LogLevel.Trace
});
var sub = client.Futures.SubscribeToPositionUpdatesAsync("DENTUSDTM", data =>
{
    var originalData = data.OriginalData;
    var topic = data.Topic;
    var fetchData = data.Data;
});
```

Image of data that is empty:
![image](https://user-images.githubusercontent.com/23153570/145680147-4b111649-b043-45d7-b311-069090e0679b.png)

**Comment by shahrooztk** [comment]
> Can you check what data is sent in the socket?

Hi again @JKorf .
I have a problem with this method and all data is null.
I open a new position, then make changes to it (manually) , But this socket method does not seem to pay attention to the opening and closing of my positions or their moment-by-moment reporting in my account.

I will send you code and the pictures related to the tests I did. Check to see the problem of my work.

I created a position manually in currency, In my Kucoin Futures account (DENTUSDTM). Then i used SubscribeToPositionUpdatesAsync  method but all data is null.

This is my code:
```
var client = new KucoinSocketClient(new KucoinSocketClientOptions() 
{
    FuturesApiCredentials = new KucoinApiCredentials("******", "******", "******"),
    OutputOriginalData = true,
    LogLevel = Microsoft.Extensions.Logging.LogLevel.Trace
});
var sub = client.Futures.SubscribeToPositionUpdatesAsync("DENTUSDTM", data =>
{
    var originalData = data.OriginalData;
    var topic = data.Topic;
    var fetchData = data.Data;
});
```

Image of data that is empty:
![image](https://user-images.githubusercontent.com/23153570/145701323-36448808-861a-48ee-9065-9950fc670146.png)

**Comment by hyperms** [comment]
I have exactly the same problem

**Comment by JKorf** [comment]
You're right. Based on the type of position update different data is returned from the server. In this case, only a `sum` property is send, so the position model will not get filled at all. 
I'll fix this, it will need to have different handlers for the different types of updates

**Comment by JKorf** [comment]
I've created a new version (3.2.0) in which this should be fixed

**Comment by shahrooztk** [comment]
> I've created a new version (3.2.0) in which this should be fixed

Thanks JKorf.
I use Binance.net and Kucoin.net . I have no problem with your Binance service and that's excellent, but I have problems with Kucoin service and I think it's not as perfect as Binance.

I'm currently using your latest version (3.1.6 ) and these problems persists.

Due to the great progress of Kucoin in recent months, I hope that with your help, these problems are fixed and service the same as Binance.net will be developed and made available to the audience.

**Comment by hyperms** [comment]
> I've created a new version (3.2.0) in which this should be fixed

Thank you, but still onPositionUpdate is not triggered when I opening or closing an position.

**Comment by hyperms** [comment]
> @hyperms Can you share some code and logging from subscribing on the client and placing the order? You can enable trace logging to see the send/received data by setting LogLevel to Trace in the client options

I finally found the solution.
The "changeReason" field is in the "Data.data" object, not in the "Data" object.

```
 public async Task<CallResult<UpdateSubscription>> SubscribeToPositionUpdatesAsync(
            string symbol,
            Action<DataEvent<KucoinPositionUpdate>> onPositionUpdate,
            Action<DataEvent<KucoinPositionMarkPriceUpdate>> onMarkPriceUpdate,
            Action<DataEvent<KucoinPositionFundingSettlementUpdate>> onFundingSettlementUpdate,
            Action<DataEvent<KucoinPositionRiskAdjustResultUpdate>> onRiskAdjustUpdate)
        {
            var innerHandler = new Action<DataEvent<JToken>>(tokenData =>
            {
                var subject = tokenData.Data["subject"]?.ToString();
                if (subject == "position.change")
                {
                    if (tokenData.Data["data"]["changeReason"] == null || tokenData.Data["data"]["changeReason"].ToString() == "markPriceChange")
                    {
                        var data = GetData<KucoinPositionMarkPriceUpdate>(tokenData);
                        InvokeHandler(tokenData.As(data, symbol), onMarkPriceUpdate);
                    }
                    else if (tokenData.Data["data"]["changeReason"].ToString() == "positionChange")
                    {
                        var data = GetData<KucoinPositionUpdate>(tokenData);
                        InvokeHandler(tokenData.As(data, symbol), onPositionUpdate);
                    }
                }
                else if (subject == "position.settlement")
                {
                    var data = GetData<KucoinPositionFundingSettlementUpdate>(tokenData);
                    InvokeHandler(tokenData.As(data, symbol), onFundingSettlementUpdate);
                }
                else if (subject == "position.adjustRiskLimit")
                {
                    var data = GetData<KucoinPositionRiskAdjustResultUpdate>(tokenData);
                    InvokeHandler(tokenData.As(data, symbol), onRiskAdjustUpdate);
                }
                else
                    log.Write(LogLevel.Warning, $"Unknown update: {subject}, data: {tokenData}");
            });

            var request = new KucoinRequest(NextId().ToString(CultureInfo.InvariantCulture), "subscribe", $"/contract/position:" + symbol, true);
            return await SubscribeAsync("futures", request, null, true, innerHandler).ConfigureAwait(false);
        }
```

**Comment by hyperms** [comment]
Actually, SubscribeToBalanceUpdatesAsync does not work either

**Comment by hyperms** [comment]
> Actually, SubscribeToBalanceUpdatesAsync does not work either

This is because SubscribeToBalanceUpdatesAsync is a private channel but it implemented as a public channel here.

```
public async Task<CallResult<UpdateSubscription>> SubscribeToBalanceUpdatesAsync(
            Action<DataEvent<KucoinStreamOrderMarginUpdate>> onOrderMarginUpdate,
            Action<DataEvent<KucoinStreamFuturesBalanceUpdate>> onBalanceUpdate,
            Action<DataEvent<KucoinStreamFuturesWithdrawableUpdate>> onWithdrawableUpdate)
        {
            var innerHandler = new Action<DataEvent<JToken>>(tokenData =>
            {
                var subject = tokenData.Data["subject"]?.ToString();
                if (subject == "orderMargin.change")
                {
                    var data = GetData<KucoinStreamOrderMarginUpdate>(tokenData);
                    InvokeHandler(tokenData.As(data, data.Currency), onOrderMarginUpdate);
                }
                else if (subject == "availableBalance.change")
                {
                    var data = GetData<KucoinStreamFuturesBalanceUpdate>(tokenData);
                    InvokeHandler(tokenData.As(data, data.Currency), onBalanceUpdate);
                }
                else if (subject == "withdrawHold.change")
                {
                    var data = GetData<KucoinStreamFuturesWithdrawableUpdate>(tokenData);
                    InvokeHandler(tokenData.As(data, data.Currency), onWithdrawableUpdate);
                }
                else
                    log.Write(LogLevel.Warning, "Unknown update: " + subject);
            });

            var request = new KucoinRequest(NextId().ToString(CultureInfo.InvariantCulture), "subscribe", $"/contractAccount/wallet", true);
            return await SubscribeAsync("futures", request, null, true, innerHandler).ConfigureAwait(false);
        }
```

**Comment by JKorf** [comment]
Hi again. I've pushed version 3.2.1. It works for me, let me know if you have any issues.
Sorry for the inconvenience!

**Comment by hyperms** [comment]
Thanks a lot @JKorf !
This issue seems to be solved and can be closed.

**Comment by hyperms** [comment]
Thanks a lot @JKorf 
This issue seems to be solved and can be closed.

**Comment by shahrooztk** [comment]
Thanks @JKorf 
I will try this update and let you know again.

**Comment by shahrooztk** [comment]
Hi again @JKorf 
I checked this update and understood fixed this bug very well.
I work on my project and if I seen bug will definitely inform you again. 
Thanks a lot.
